# Introduction

In this guide we will analyse some of the most commonly used and powerful machine learning algorithms. We will walk
through the intuition behind each algorithm, the required mathematical background, as well as its implementation in R,
in a step by step approach. We will discuss and implement optimisation techniques, explain use cases, measure their
performance and understand how to interpret and use their outcomes. On top of that, the guide is accompanied by live
applications that make use the algorithms to help you understand their value, advantages and drawbacks of various
approaches. This guide does not require any prior knowledge, although some basic mathematical and programming background
would make things easier. For those that need to occasionally refresh their statistics, there is a chapter devoted to
that.

This guide refers to anyone who is interested in machine learning, from any background. We will go far beyond the basics
of use cases and implementation of each algorithm, however at no point will there be anything presented that assumes
previous knowledge and is not accompanied by real case examples and implementations.

My inspiration for creating this, was the book 'An introduction to Statistical Learning' written by Gareth James,
Daniela Witten, Trevor Hastie and Robert Tibshirani, which I would highly recommend. It contains labs and exercises for
your learning, as well as an approachable explanation of machine learning algorithms. We will be referring to that book
and other resources through the guide.
