---
title: "Machine Learning Algorithms Guide"
author: "Sofia Kyriazidi"
date: "`r Sys.time()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: chicsof/machine_learning_algorithms_guide
description: "In this guide we will analyse some of the most commonly used and powerful machine learning algorithms. We will walk through the intuition behind each algorithm, the required mathematical background, as well as its implementation in R, in a step by step approach."
---

# Introduction

In this guide we will analyse some of the most commonly used and powerful machine learning algorithms. We will walk
through the intuition behind each algorithm, the required mathematical background, as well as its implementation in R,
in a step by step approach. We will discuss and implement optimisation techniques, explain use cases, measure their
performance and understand how to interpret and use their outcomes. On top of that, the guide is accompanied by live
applications that make use the algorithms to help you understand their value, advantages and drawbacks of various
approaches. This guide does not require any prior knowledge, although some basic mathematical and programming background
would make things easier. For those that need to occasionally refresh their statistics, there is a chapter devoted to
that.

Chapters coming up up soon:

* General Additive Models (GAMs)

* Bayer's for Classification

* Other classification Algorithms (k-means and knn)

* Deception Trees

* Support-Vector Machines

* Boosting

For any queries contact at: sophia.97@windowslive.com

Credits should be given to to the book 'An introduction to Statistical Learning' written by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani, which helped a lot in my learning and origination of this project. We will be referring to this book and other resources thought the guide.
